# Generated by dev_portal — thin runtime image.
# Run `mvn -DskipTests package` (or kick a portal deep build) before `docker build .`.
FROM eclipse-temurin:21-jre
WORKDIR /app
ARG JAR_FILE=log-search-service/target/log-search-service-*.jar
COPY ${JAR_FILE} /app/app.jar

# Index, H2 database, and tailer state all live under /data — mount a host volume here
# to persist them across pod restarts. /host is the read-only window onto the host
# filesystem; configure log sources in the app to point at /host/... paths.
RUN mkdir -p /data/indices /data/database /data/state /host
VOLUME ["/data"]

EXPOSE 8080
ENV JAVA_OPTS="" \
    INDEX_BASE_DIRECTORY=/data/indices \
    STATE_DIR=/data/state \
    SPRING_DATASOURCE_URL="jdbc:h2:file:/data/database/logdb;AUTO_SERVER=TRUE"
ENTRYPOINT ["sh", "-c", "exec java $JAVA_OPTS -jar /app/app.jar"]
